// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHAhCUE1lv93PJ_tAIHAol-iXQYrIFeAk',
    appId: '1:608702054226:web:8874b451e1bec42d18848b',
    messagingSenderId: '608702054226',
    projectId: 'scout-app-bf566',
    authDomain: 'scout-app-bf566.firebaseapp.com',
    storageBucket: 'scout-app-bf566.firebasestorage.app',
    measurementId: 'G-55SZ8EH5ZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9SsxPpnUrYZMWFwkQ2Zc7KNsIl_w8hNc',
    appId: '1:608702054226:android:7d34b00e884a275f18848b',
    messagingSenderId: '608702054226',
    projectId: 'scout-app-bf566',
    storageBucket: 'scout-app-bf566.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPIhlw2L7GEU-kcSQoVjKL_ke7eiLvRZc',
    appId: '1:608702054226:ios:a090ca85afacfea818848b',
    messagingSenderId: '608702054226',
    projectId: 'scout-app-bf566',
    storageBucket: 'scout-app-bf566.firebasestorage.app',
    iosBundleId: 'com.example.scoutApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPIhlw2L7GEU-kcSQoVjKL_ke7eiLvRZc',
    appId: '1:608702054226:ios:a090ca85afacfea818848b',
    messagingSenderId: '608702054226',
    projectId: 'scout-app-bf566',
    storageBucket: 'scout-app-bf566.firebasestorage.app',
    iosBundleId: 'com.example.scoutApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHAhCUE1lv93PJ_tAIHAol-iXQYrIFeAk',
    appId: '1:608702054226:web:803c14fe51d3a22f18848b',
    messagingSenderId: '608702054226',
    projectId: 'scout-app-bf566',
    authDomain: 'scout-app-bf566.firebaseapp.com',
    storageBucket: 'scout-app-bf566.firebasestorage.app',
    measurementId: 'G-PZ7R9HFET0',
  );
}
